# Generated by cucumber-sinatra. (2014-02-10 11:42:13 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/bookmark-manager.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = BoomarkManager

class BoomarkManagerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BoomarkManagerWorld.new
end
